import type { ItemDef } from '@/types/content'

export const items: ItemDef[] = [
  {
    id: 'ration',
    name: '压缩饼干',
    emoji: '🥫',
    description: '味道像纸板，但能填肚子。',
    weight: 0.3,
    stackable: true,
    usable: true,
    useEffects: [
      { type: 'modAttr', attr: 'hunger', delta: 25 },
      { type: 'modSan', delta: 1 },
    ],
    tags: ['food'],
  },
  {
    id: 'water_bottle',
    name: '饮用水',
    emoji: '💧',
    description: '半瓶温热的水。',
    weight: 0.5,
    stackable: true,
    usable: true,
    useEffects: [{ type: 'modAttr', attr: 'thirst', delta: 30 }],
    tags: ['drink'],
  },
  {
    id: 'knife',
    name: '求生刀',
    emoji: '🔪',
    description: '刃口有缺口，仍能劈砍。',
    weight: 0.6,
    equipSlot: 'hands',
    weaponType: 'melee',
    damage: 8,
  },
  {
    id: 'rope',
    name: '绳索',
    emoji: '🪢',
    description: '结实的尼龙绳。',
    weight: 0.8,
    stackable: true,
  },
  {
    id: 'wood',
    name: '木材',
    emoji: '🪵',
    description: '潮湿但还能用的木料。',
    weight: 1.2,
    stackable: true,
    maxStack: 20,
  },
  {
    id: 'scrap_metal',
    name: '金属碎片',
    emoji: '🔩',
    description: '飞机残骸上敲下来的。',
    weight: 1,
    stackable: true,
  },
  {
    id: 'spear',
    name: '简易长矛',
    emoji: '🗡️',
    description: '削尖的木杆绑着金属尖。',
    weight: 1.5,
    equipSlot: 'hands',
    weaponType: 'melee',
    damage: 10,
    tags: ['spear'],
  },
  {
    id: 'camp_kit',
    name: '露营工具',
    emoji: '⛺',
    description: '可以就地扎营。',
    weight: 2,
    stackable: true,
  },
  {
    id: 'bandage',
    name: '绷带',
    emoji: '🩹',
    description: '止血包扎。',
    weight: 0.2,
    stackable: true,
    usable: true,
    useEffects: [{ type: 'heal', amount: 15 }],
  },
  {
    id: 'mutant_hide',
    name: '变异兽皮',
    emoji: '🦴',
    description: '摸上去温热，仿佛还活着。',
    weight: 1.5,
    stackable: true,
  },
  {
    id: 'charges',
    name: '实验性炸药',
    emoji: '💣',
    description: '研究基地留下的不稳定装置。',
    weight: 3,
  },
  {
    id: 'cloth',
    name: '破布',
    emoji: '🧵',
    description: '可以做成绷带或衣物衬里。',
    weight: 0.2,
    stackable: true,
  },
  {
    id: 'warm_cloak',
    name: '兽皮披风',
    emoji: '🧥',
    description: '提供保暖。',
    weight: 2,
    equipSlot: 'body',
    armor: 2,
    warmth: 15,
  },
  {
    id: 'watch',
    name: '机械手表',
    emoji: '⌚',
    description: '还在走的旧手表。能让你知道准确时间。',
    weight: 0.1,
    equipSlot: 'accessory',
    tags: ['timepiece'],
  },
  {
    id: 'latiao',
    name: '辣条',
    emoji: '🌶️',
    description: '香辣可口的豆制品零食，虽然过期但风味依旧。',
    weight: 0.1,
    stackable: true,
    usable: true,
    useEffects: [
      { type: 'modAttr', attr: 'hunger', delta: 10 },
      { type: 'modAttr', attr: 'stamina', delta: 10 },
      { type: 'heal', amount: 1 },
    ],
    tags: ['food'],
  },
  {
    id: 'instant_noodles',
    name: '方便面',
    emoji: '🍜',
    description: '冲泡即食的面饼，虽然只有调味包但能快速补充体力。',
    weight: 0.3,
    stackable: true,
    usable: true,
    useEffects: [
      { type: 'modAttr', attr: 'hunger', delta: 20 },
      { type: 'modAttr', attr: 'stamina', delta: 20 },
      { type: 'heal', amount: 100 },
    ],
    tags: ['food'],
  },
  {
    id: 'baseball_bat',
    name: '棒球棒',
    emoji: '🔨',
    description: '木质棒球棒，适合用来防身。',
    weight: 1.8,
    equipSlot: 'hands',
    weaponType: 'melee',
    damage: 20,
    tags: ['bat'],
  },
  {
    id: 'backpack',
    name: '背包',
    emoji: '🎒',
    description: '军用战术背包，能增加携带上限。',
    weight: 0.5,
    equipSlot: 'accessory',
    tags: ['capacity'],
  },
  {
    id: 'san_monitor',
    name: 'SAN显示仪',
    emoji: '📊',
    description: '基金会遗留的小型设备，能显示当前SAN值。',
    weight: 0.2,
    equipSlot: 'accessory',
    tags: ['san_display'],
  },
  {
    id: 'protective_suit',
    name: '防护服',
    emoji: '🥼',
    description: '基金会研究员的防护服，能提供基础防护。',
    weight: 2.5,
    equipSlot: 'body',
    armor: 10,
    warmth: 5,
  },
  {
    id: 'tattered_map',
    name: '残破地图',
    emoji: '🗺️',
    description: '一张残破的地图，标记着丛林的入口位置。',
    weight: 0.1,
    stackable: true,
    tags: ['key_item'],
  },
]
