// 定义所有物品、装备、武器配置
// 包括：物品id、类型、名称、描述、属性、效果、重量、耐久度、堆叠等
// config/items.ts - 物品配置实例（最小可验证集合）

import type { Item, ItemRegistry } from '../types/item'
import { ItemCategory, ItemRarity, EquipmentSlot, ConsumableType, MaterialType } from '../types/item'
import { RecipeType } from '../types/recipe'
import type { AttributeType } from '../types/effect'

const items: Record<string, Item> = {
  // ============================================================
  // 武器
  // ============================================================
  item_rusty_sword: {
    id: 'item_rusty_sword',
    name: '锈剑',
    description: '一把生锈的铁剑，虽然状况不佳，但仍能用来防身',
    category: ItemCategory.WEAPON,
    rarity: ItemRarity.COMMON,
    iconId: 'icon_rusty_sword',
    weight: 2.5,
    maxStackSize: 1,
    isSellable: true,
    basePrice: 15,
    isKeyItem: false,
    tags: ['weapon', 'sword', 'metal', 'starter'],
    weaponTypeId: 'sword',
    durability: {
      maxDurability: 50,
      initialDurability: 35,
      isRepairable: true,
      repairMaterials: [{ itemId: 'item_scrap_metal', quantity: 2 }],
      repairWorkbenchLevel: 1,
      destroyOnBreak: false,
      brokenItemId: 'item_broken_sword',
    },
    equipmentSlot: EquipmentSlot.WEAPON,
    weaponStats: {
      baseDamage: 10,
      damageTypeId: 'slash',
      damageVariance: 0.15,
      attackRange: 1,
      accuracyModifier: 0.05,
      criticalChanceModifier: 0.03,
      criticalMultiplier: 2.0,
      attackSpeed: 0.95,
      staminaCostPerAttack: 12,
    },
    isDualWieldable: false,
    isTwoHanded: false,
  },

  item_survival_knife: {
    id: 'item_survival_knife',
    name: '生存刀',
    description: '一把多功能求生刀，既可战斗也可用于采集和制作',
    category: ItemCategory.WEAPON,
    rarity: ItemRarity.UNCOMMON,
    iconId: 'icon_survival_knife',
    weight: 0.8,
    maxStackSize: 1,
    isSellable: false,
    basePrice: 30,
    isKeyItem: false,
    tags: ['weapon', 'dagger', 'tool', 'starter'],
    weaponTypeId: 'dagger',
    durability: {
      maxDurability: 80,
      initialDurability: 80,
      isRepairable: true,
      repairMaterials: [{ itemId: 'item_scrap_metal', quantity: 1 }],
      repairWorkbenchLevel: 1,
      destroyOnBreak: false,
      brokenItemId: 'item_broken_knife',
    },
    equipmentSlot: EquipmentSlot.WEAPON,
    weaponStats: {
      baseDamage: 8,
      damageTypeId: 'pierce',
      damageVariance: 0.1,
      attackRange: 1,
      accuracyModifier: 0.15,
      criticalChanceModifier: 0.12,
      criticalMultiplier: 2.8,
      attackSpeed: 1.4,
      staminaCostPerAttack: 7,
    },
    isDualWieldable: true,
    isTwoHanded: false,
    attributeModifiers: [
      { attribute: 'gathering' as AttributeType, modifierType: 'add', value: 1, subType: 'gathering' },
    ],
    grantedPassiveIds: ['quick_hands'],
  },

  item_wooden_spear: {
    id: 'item_wooden_spear',
    name: '木矛',
    description: '一根削尖的木棍，简陋但能让敌人保持距离',
    category: ItemCategory.WEAPON,
    rarity: ItemRarity.COMMON,
    iconId: 'icon_wooden_spear',
    weight: 2.0,
    maxStackSize: 1,
    isSellable: true,
    basePrice: 5,
    isKeyItem: false,
    tags: ['weapon', 'spear', 'wood', 'craftable'],
    weaponTypeId: 'spear',
    durability: {
      maxDurability: 30,
      initialDurability: 30,
      isRepairable: false,
      destroyOnBreak: true,
    },
    equipmentSlot: EquipmentSlot.WEAPON,
    weaponStats: {
      baseDamage: 12,
      damageTypeId: 'pierce',
      damageVariance: 0.15,
      attackRange: 2,
      accuracyModifier: 0.0,
      criticalChanceModifier: 0.05,
      criticalMultiplier: 2.0,
      attackSpeed: 0.8,
      staminaCostPerAttack: 14,
    },
    isDualWieldable: false,
    isTwoHanded: true,
  },

  item_broken_sword: {
    id: 'item_broken_sword',
    name: '损坏的锈剑',
    description: '已经完全断裂的锈剑，或许可以熔炼回收一些金属',
    category: ItemCategory.MISC,
    rarity: ItemRarity.COMMON,
    iconId: 'icon_broken_sword',
    weight: 1.5,
    maxStackSize: 1,
    isSellable: true,
    basePrice: 3,
    isKeyItem: false,
    tags: ['broken', 'metal', 'salvage'],
    isCombinable: false,
  },

  item_broken_knife: {
    id: 'item_broken_knife',
    name: '损坏的生存刀',
    description: '刀刃已经卷曲的生存刀，需要修理才能使用',
    category: ItemCategory.MISC,
    rarity: ItemRarity.COMMON,
    iconId: 'icon_broken_knife',
    weight: 0.6,
    maxStackSize: 1,
    isSellable: true,
    basePrice: 5,
    isKeyItem: false,
    tags: ['broken', 'metal', 'salvage'],
    isCombinable: false,
  },

  // ============================================================
  // 防具
  // ============================================================
  item_tattered_clothes: {
    id: 'item_tattered_clothes',
    name: '破旧衣物',
    description: '飞机失事后身上仅存的衣物，几乎没有防护能力，但聊胜于无',
    category: ItemCategory.ARMOR,
    rarity: ItemRarity.COMMON,
    iconId: 'icon_tattered_clothes',
    weight: 0.5,
    maxStackSize: 1,
    isSellable: false,
    basePrice: 1,
    isKeyItem: false,
    tags: ['armor', 'cloth', 'starter'],
    durability: {
      maxDurability: 20,
      initialDurability: 10,
      isRepairable: true,
      repairMaterials: [{ itemId: 'item_cloth_scrap', quantity: 2 }],
      destroyOnBreak: true,
    },
    equipmentSlot: EquipmentSlot.BODY,
    defenseStats: {
      slashDefense: 3,
      bluntDefense: 1,
      rangedDefense: 1,
      poisonDefense: 0,
      fireDefense: 0,
    },
    temperatureResistance: {
      lowModifier: -2,
      highModifier: 0,
    },
  },

  item_leather_vest: {
    id: 'item_leather_vest',
    name: '皮革背心',
    description: '用变异野兽的皮缝制的简易护甲，比破布强不少',
    category: ItemCategory.ARMOR,
    rarity: ItemRarity.COMMON,
    iconId: 'icon_leather_vest',
    weight: 3.0,
    maxStackSize: 1,
    isSellable: true,
    basePrice: 25,
    isKeyItem: false,
    tags: ['armor', 'leather', 'craftable'],
    durability: {
      maxDurability: 60,
      initialDurability: 60,
      isRepairable: true,
      repairMaterials: [{ itemId: 'item_leather_scrap', quantity: 3 }],
      repairWorkbenchLevel: 1,
      destroyOnBreak: true,
    },
    equipmentSlot: EquipmentSlot.BODY,
    defenseStats: {
      slashDefense: 10,
      bluntDefense: 5,
      rangedDefense: 5,
      poisonDefense: 0,
      fireDefense: 0,
    },
    temperatureResistance: {
      lowModifier: -5,
      highModifier: 0,
    },
  },

  // ============================================================
  // 工具
  // ============================================================
  item_hand_axe: {
    id: 'item_hand_axe',
    name: '手斧',
    description: '一把伐木手斧，砍树效率不错，紧急时也能当武器',
    category: ItemCategory.TOOL,
    rarity: ItemRarity.COMMON,
    iconId: 'icon_hand_axe',
    weight: 2.0,
    maxStackSize: 1,
    isSellable: true,
    basePrice: 20,
    isKeyItem: false,
    tags: ['tool', 'axe', 'woodcutting'],
    durability: {
      maxDurability: 80,
      initialDurability: 80,
      isRepairable: true,
      repairMaterials: [{ itemId: 'item_scrap_metal', quantity: 1 }, { itemId: 'item_wood', quantity: 2 }],
      repairWorkbenchLevel: 1,
      destroyOnBreak: false,
      brokenItemId: 'item_broken_axe',
    },
    equipmentSlot: EquipmentSlot.TOOL,
    toolTypeId: 'axe',
    toolLevel: 1,
    skillBonuses: [
      { skillId: 'woodcutting', bonus: 2 },
    ],
    specialFunctions: ['可以砍伐中型树木', '可以作为临时武器使用'],
  },

  item_torch: {
    id: 'item_torch',
    name: '火把',
    description: '简易火把，提供光照和温暖，但燃烧时间有限',
    category: ItemCategory.TOOL,
    rarity: ItemRarity.COMMON,
    iconId: 'icon_torch',
    weight: 0.5,
    maxStackSize: 5,
    isSellable: true,
    basePrice: 3,
    isKeyItem: false,
    tags: ['tool', 'light', 'fire', 'craftable'],
    durability: {
      maxDurability: 30,
      initialDurability: 30,
      isRepairable: false,
      destroyOnBreak: true,
      performanceDegradation: {
        enabled: true,
        threshold: 0.2,
        maxDegradation: 0.5,
      },
    },
    equipmentSlot: EquipmentSlot.LIGHT,
    toolTypeId: 'torch',
    toolLevel: 1,
    specialFunctions: ['提供光照', '略微提升周围温度', '可以引燃可燃物'],
  },

  item_fishing_rod: {
    id: 'item_fishing_rod',
    name: '简易鱼竿',
    description: '用树枝和藤蔓制作的钓鱼工具，能不能钓到鱼看运气',
    category: ItemCategory.TOOL,
    rarity: ItemRarity.COMMON,
    iconId: 'icon_fishing_rod',
    weight: 0.8,
    maxStackSize: 1,
    isSellable: true,
    basePrice: 10,
    isKeyItem: false,
    tags: ['tool', 'fishing', 'craftable'],
    durability: {
      maxDurability: 40,
      initialDurability: 40,
      isRepairable: true,
      repairMaterials: [{ itemId: 'item_vine', quantity: 1 }],
      destroyOnBreak: true,
    },
    equipmentSlot: EquipmentSlot.TOOL,
    toolTypeId: 'fishingRod',
    toolLevel: 1,
    skillBonuses: [
      { skillId: 'fishing', bonus: 1 },
    ],
    specialFunctions: ['可以在水边钓鱼'],
  },

  // ============================================================
  // 消耗品
  // ============================================================
  item_bandage: {
    id: 'item_bandage',
    name: '绷带',
    description: '用布料撕成的简易绷带，可以包扎伤口止血',
    category: ItemCategory.CONSUMABLE,
    rarity: ItemRarity.COMMON,
    iconId: 'icon_bandage',
    weight: 0.1,
    maxStackSize: 10,
    isSellable: true,
    basePrice: 5,
    isKeyItem: false,
    tags: ['consumable', 'medicine', 'craftable'],
    consumableType: ConsumableType.MEDICINE,
    useTimeMinutes: 2,
    effects: [
      {
        effect: {
          type: 'attribute',
          attribute: 'hp',
          operation: 'add',
          value: 15,
        } as any,
        description: '恢复15点生命值',
      },
      {
        effect: {
          type: 'status',
          statusId: 'bleed',
          apply: false,
        } as any,
        description: '移除流血状态',
      },
    ],
  },

  item_antibiotic: {
    id: 'item_antibiotic',
    name: '抗生素',
    description: '从飞机急救箱中找到的广谱抗生素，可治疗感染',
    category: ItemCategory.CONSUMABLE,
    rarity: ItemRarity.UNCOMMON,
    iconId: 'icon_antibiotic',
    weight: 0.05,
    maxStackSize: 5,
    isSellable: true,
    basePrice: 40,
    isKeyItem: false,
    tags: ['consumable', 'medicine', 'rare'],
    consumableType: ConsumableType.MEDICINE,
    useTimeMinutes: 1,
    effects: [
      {
        effect: {
          type: 'status',
          statusId: 'infection',
          apply: false,
        } as any,
        description: '移除感染状态',
      },
    ],
    useText: '你吞下一粒抗生素，希望它能对抗体内的感染。',
  },

  item_cooked_fish: {
    id: 'item_cooked_fish',
    name: '烤鱼',
    description: '在篝火上烤熟的鱼，散发着诱人的香气',
    category: ItemCategory.CONSUMABLE,
    rarity: ItemRarity.COMMON,
    iconId: 'icon_cooked_fish',
    weight: 0.3,
    maxStackSize: 5,
    isSellable: true,
    basePrice: 8,
    isKeyItem: false,
    tags: ['consumable', 'food', 'cooked'],
    consumableType: ConsumableType.FOOD,
    useTimeMinutes: 5,
    effects: [
      {
        effect: {
          type: 'attribute',
          attribute: 'satiety',
          operation: 'add',
          value: 25,
        } as any,
        description: '恢复25点饱食度',
      },
      {
        effect: {
          type: 'attribute',
          attribute: 'san',
          operation: 'add',
          value: 3,
        } as any,
        probability: 0.3,
        description: '温暖的食物有30%概率恢复3点SAN值',
      },
    ],
    useText: '你大口吃着烤鱼，虽然味道一般，但热食总是让人安心。',
  },

  item_clean_water: {
    id: 'item_clean_water',
    name: '清水',
    description: '经过净化的饮用水，生存的必需品',
    category: ItemCategory.CONSUMABLE,
    rarity: ItemRarity.COMMON,
    iconId: 'icon_clean_water',
    weight: 0.5,
    maxStackSize: 10,
    isSellable: true,
    basePrice: 3,
    isKeyItem: false,
    tags: ['consumable', 'drink', 'essential'],
    consumableType: ConsumableType.DRINK,
    useTimeMinutes: 1,
    effects: [
      {
        effect: {
          type: 'attribute',
          attribute: 'satiety',
          operation: 'add',
          value: 5,
        } as any,
        description: '略微缓解口渴',
      },
    ],
  },

  // ============================================================
  // 材料
  // ============================================================
  item_wood: {
    id: 'item_wood',
    name: '木材',
    description: '普通的木柴，可用于建造、制作和燃烧',
    category: ItemCategory.MATERIAL,
    rarity: ItemRarity.COMMON,
    iconId: 'icon_wood',
    weight: 1.0,
    maxStackSize: 20,
    isSellable: true,
    basePrice: 1,
    isKeyItem: false,
    tags: ['material', 'wood', 'fuel'],
    materialType: MaterialType.WOOD,
    materialTier: 1,
    burnTimeMinutes: 15,
    grantsExpOnCollect: {
      skillTypeId: 'woodcutting',
      expAmount: 5,
    },
  },

  item_stone: {
    id: 'item_stone',
    name: '石头',
    description: '随处可见的石头，建造和制作的基础材料',
    category: ItemCategory.MATERIAL,
    rarity: ItemRarity.COMMON,
    iconId: 'icon_stone',
    weight: 2.0,
    maxStackSize: 10,
    isSellable: true,
    basePrice: 1,
    isKeyItem: false,
    tags: ['material', 'stone'],
    materialType: MaterialType.STONE,
    materialTier: 1,
    burnTimeMinutes: 0,
    grantsExpOnCollect: {
      skillTypeId: 'mining',
      expAmount: 5,
    },
  },

  item_vine: {
    id: 'item_vine',
    name: '藤蔓',
    description: '坚韧的藤蔓纤维，可用于捆绑和制作绳索',
    category: ItemCategory.MATERIAL,
    rarity: ItemRarity.COMMON,
    iconId: 'icon_vine',
    weight: 0.3,
    maxStackSize: 20,
    isSellable: true,
    basePrice: 1,
    isKeyItem: false,
    tags: ['material', 'fiber'],
    materialType: MaterialType.FIBER,
    materialTier: 1,
    burnTimeMinutes: 5,
    grantsExpOnCollect: {
      skillTypeId: 'gathering',
      expAmount: 3,
    },
  },

  item_herb: {
    id: 'item_herb',
    name: '草药',
    description: '岛上常见的野生草药，可以制作简易药品',
    category: ItemCategory.MATERIAL,
    rarity: ItemRarity.COMMON,
    iconId: 'icon_herb',
    weight: 0.1,
    maxStackSize: 15,
    isSellable: true,
    basePrice: 3,
    isKeyItem: false,
    tags: ['material', 'herb', 'medicine'],
    materialType: MaterialType.HERB,
    materialTier: 1,
    burnTimeMinutes: 3,
    grantsExpOnCollect: {
      skillTypeId: 'gathering',
      expAmount: 8,
    },
  },

  item_raw_fish: {
    id: 'item_raw_fish',
    name: '生鱼',
    description: '刚从水里捞上来的鱼，需要煮熟才能安全食用',
    category: ItemCategory.MATERIAL,
    rarity: ItemRarity.COMMON,
    iconId: 'icon_raw_fish',
    weight: 0.5,
    maxStackSize: 8,
    isSellable: true,
    basePrice: 5,
    isKeyItem: false,
    tags: ['material', 'foodRaw', 'perishable'],
    materialType: MaterialType.FOOD_RAW,
    materialTier: 1,
    burnTimeMinutes: 0,
  },

  item_cloth_scrap: {
    id: 'item_cloth_scrap',
    name: '布料碎片',
    description: '从衣物或残骸上撕下的布料，可用于制作绷带或修补衣物',
    category: ItemCategory.MATERIAL,
    rarity: ItemRarity.COMMON,
    iconId: 'icon_cloth_scrap',
    weight: 0.2,
    maxStackSize: 15,
    isSellable: true,
    basePrice: 2,
    isKeyItem: false,
    tags: ['material', 'fiber', 'cloth'],
    materialType: MaterialType.FIBER,
    materialTier: 1,
    burnTimeMinutes: 8,
  },

  item_scrap_metal: {
    id: 'item_scrap_metal',
    name: '金属碎片',
    description: '从飞机残骸上回收的金属碎片，修理和制作的基础材料',
    category: ItemCategory.MATERIAL,
    rarity: ItemRarity.COMMON,
    iconId: 'icon_scrap_metal',
    weight: 1.5,
    maxStackSize: 10,
    isSellable: true,
    basePrice: 5,
    isKeyItem: false,
    tags: ['material', 'metal'],
    materialType: MaterialType.METAL,
    materialTier: 1,
    burnTimeMinutes: 0,
  },

  item_leather_scrap: {
    id: 'item_leather_scrap',
    name: '皮革碎片',
    description: '从变异野兽身上剥下的皮革，可用于制作护甲',
    category: ItemCategory.MATERIAL,
    rarity: ItemRarity.COMMON,
    iconId: 'icon_leather_scrap',
    weight: 0.8,
    maxStackSize: 10,
    isSellable: true,
    basePrice: 8,
    isKeyItem: false,
    tags: ['material', 'leather'],
    materialType: MaterialType.LEATHER,
    materialTier: 1,
    burnTimeMinutes: 10,
  },

  // ============================================================
  // 贵重物品
  // ============================================================
  item_gold_coin: {
    id: 'item_gold_coin',
    name: '金币',
    description: '在这个被遗弃的岛屿上意外发现的古老金币，不知出自何人之手',
    category: ItemCategory.VALUABLE,
    rarity: ItemRarity.UNCOMMON,
    iconId: 'icon_gold_coin',
    weight: 0.01,
    maxStackSize: 999,
    isSellable: true,
    basePrice: 10,
    isKeyItem: false,
    tags: ['valuable', 'currency'],
    priceMultiplier: 1.0,
  },

  // ============================================================
  // 文档
  // ============================================================
  item_journal_fragment: {
    id: 'item_journal_fragment',
    name: '研究笔记残页',
    description: '一张泛黄的纸，上面潦草地写满了看不懂的公式和疯狂的涂鸦',
    category: ItemCategory.DOCUMENT,
    rarity: ItemRarity.UNCOMMON,
    iconId: 'icon_journal_fragment',
    weight: 0.05,
    maxStackSize: 1,
    isSellable: false,
    basePrice: 0,
    isKeyItem: false,
    tags: ['document', 'lore'],
    content: '第37天：孢子仍在扩散。收容措施完全失效。我们低估了它的适应能力。\n\n第42天：有人开始听到声音。我也听到了。它们不是幻觉。\n\n第45天：塔必须被修复。如果有人读到这个——不要相信你所看到的。信号可以穿透屏障。在一切都太晚之前。',
    onReadEffects: [
      {
        effect: {
          type: 'flag',
          flagId: 'truth_discovered',
          operation: 'set',
          value: true,
        } as any,
        description: '你得知了部分真相',
      },
    ],
    isConsumedOnRead: false,
    readTimeMinutes: 3,
    author: '未知研究员',
  },

  // ============================================================
  // 蓝图/配方物品
  // ============================================================
  item_recipe_bandage: {
    id: 'item_recipe_bandage',
    name: '绷带制作指南',
    description: '一张皱巴巴的纸，画着如何用布料制作绷带的步骤',
    category: ItemCategory.RECIPE,
    rarity: ItemRarity.COMMON,
    iconId: 'icon_recipe',
    weight: 0.05,
    maxStackSize: 1,
    isSellable: false,
    basePrice: 0,
    isKeyItem: false,
    tags: ['recipe', 'craft'],
    recipeType: RecipeType.CRAFT,
    unlocksRecipeId: 'craft_bandage',
    isConsumedOnUse: true,
    learnTimeMinutes: 1,
  },

  item_recipe_campfire: {
    id: 'item_recipe_campfire',
    name: '篝火搭建说明',
    description: '记录着如何用石头和木材搭建篝火的示意图',
    category: ItemCategory.RECIPE,
    rarity: ItemRarity.COMMON,
    iconId: 'icon_recipe',
    weight: 0.05,
    maxStackSize: 1,
    isSellable: false,
    basePrice: 0,
    isKeyItem: false,
    tags: ['recipe', 'build'],
    recipeType: RecipeType.BUILD,
    unlocksRecipeId: 'build_campfire',
    isConsumedOnUse: true,
    learnTimeMinutes: 1,
  },

  // ============================================================
  // 任务物品
  // ============================================================
  item_map_fragment_1: {
    id: 'item_map_fragment_1',
    name: '地图碎片（一）',
    description: '一张被撕碎的地图的一部分，标记着岛屿东侧的地形',
    category: ItemCategory.QUEST,
    rarity: ItemRarity.UNCOMMON,
    iconId: 'icon_map_fragment',
    weight: 0.05,
    maxStackSize: 1,
    isSellable: false,
    basePrice: 0,
    isKeyItem: true,
    tags: ['quest', 'map'],
    questId: 'quest_find_map_fragments',
    isQuestCritical: true,
    removeOnQuestComplete: false,
  },
}

// ============================================================
// 按类别索引
// ============================================================

const itemsByCategory: Record<ItemCategory, string[]> = {
  [ItemCategory.WEAPON]: ['item_rusty_sword', 'item_survival_knife', 'item_wooden_spear'],
  [ItemCategory.ARMOR]: ['item_tattered_clothes', 'item_leather_vest'],
  [ItemCategory.TOOL]: ['item_hand_axe', 'item_torch', 'item_fishing_rod'],
  [ItemCategory.CONSUMABLE]: ['item_bandage', 'item_antibiotic', 'item_cooked_fish', 'item_clean_water'],
  [ItemCategory.MATERIAL]: ['item_wood', 'item_stone', 'item_vine', 'item_herb', 'item_raw_fish', 'item_cloth_scrap', 'item_scrap_metal', 'item_leather_scrap'],
  [ItemCategory.VALUABLE]: ['item_gold_coin'],
  [ItemCategory.DOCUMENT]: ['item_journal_fragment'],
  [ItemCategory.RECIPE]: ['item_recipe_bandage', 'item_recipe_campfire'],
  [ItemCategory.QUEST]: ['item_map_fragment_1'],
  [ItemCategory.MISC]: ['item_broken_sword', 'item_broken_knife'],
}

// ============================================================
// 按标签索引
// ============================================================

const itemsByTag: Record<string, string[]> = {
  'weapon': ['item_rusty_sword', 'item_survival_knife', 'item_wooden_spear'],
  'armor': ['item_tattered_clothes', 'item_leather_vest'],
  'tool': ['item_hand_axe', 'item_torch', 'item_fishing_rod'],
  'consumable': ['item_bandage', 'item_antibiotic', 'item_cooked_fish', 'item_clean_water'],
  'material': ['item_wood', 'item_stone', 'item_vine', 'item_herb', 'item_raw_fish', 'item_cloth_scrap', 'item_scrap_metal', 'item_leather_scrap'],
  'medicine': ['item_bandage', 'item_antibiotic', 'item_herb'],
  'food': ['item_cooked_fish', 'item_raw_fish'],
  'drink': ['item_clean_water'],
  'starter': ['item_rusty_sword', 'item_survival_knife', 'item_tattered_clothes'],
  'craftable': ['item_wooden_spear', 'item_leather_vest', 'item_torch', 'item_fishing_rod', 'item_bandage'],
  'fuel': ['item_wood'],
  'lore': ['item_journal_fragment'],
  'quest': ['item_map_fragment_1'],
  'perishable': ['item_raw_fish'],
  'broken': ['item_broken_sword', 'item_broken_knife'],
}

export const itemRegistry: ItemRegistry = {
  items,
  itemsByCategory,
  itemsByTag,
}