// config/seasonWeather.ts
import type { SeasonWeatherRegistry } from '../types/seasonWeather'
import { Season, SeasonPhase, TimeOfDay, WeatherType } from '../types/seasonWeather'

export const seasonWeatherRegistry: SeasonWeatherRegistry = {
  seasons: {
    [Season.SPRING]: {
      season: Season.SPRING,
      name: '春季',
      iconId: 'icon_season_spring',
      baseTemperatures: {
        [SeasonPhase.EARLY]: 5,
        [SeasonPhase.MID]: 15,
        [SeasonPhase.LATE]: 20,
      },
      phaseDurationDays: 10,
      weatherPool: {
        sunny: 0.3,
        cloudy: 0.25,
        overcast: 0.15,
        rain: 0.15,
        storm: 0.05,
        fog: 0.08,
        thunderstorm: 0.02,
      },
      description: '万物复苏的季节，气温逐渐回暖',
    },
    [Season.SUMMER]: {
      season: Season.SUMMER,
      name: '夏季',
      iconId: 'icon_season_summer',
      baseTemperatures: {
        [SeasonPhase.EARLY]: 20,
        [SeasonPhase.MID]: 30,
        [SeasonPhase.LATE]: 35,
      },
      phaseDurationDays: 10,
      weatherPool: {
        sunny: 0.4,
        cloudy: 0.2,
        overcast: 0.1,
        rain: 0.1,
        storm: 0.08,
        fog: 0.05,
        thunderstorm: 0.05,
        dust: 0.02,
      },
      description: '炎热的季节，阳光炽烈',
    },
    [Season.AUTUMN]: {
      season: Season.AUTUMN,
      name: '秋季',
      iconId: 'icon_season_autumn',
      baseTemperatures: {
        [SeasonPhase.EARLY]: 25,
        [SeasonPhase.MID]: 15,
        [SeasonPhase.LATE]: 5,
      },
      phaseDurationDays: 10,
      weatherPool: {
        sunny: 0.3,
        cloudy: 0.25,
        overcast: 0.2,
        rain: 0.1,
        fog: 0.1,
        storm: 0.03,
        thunderstorm: 0.02,
      },
      description: '收获的季节，气温逐渐下降',
    },
    [Season.WINTER]: {
      season: Season.WINTER,
      name: '冬季',
      iconId: 'icon_season_winter',
      baseTemperatures: {
        [SeasonPhase.EARLY]: -5,
        [SeasonPhase.MID]: -20,
        [SeasonPhase.LATE]: 0,
      },
      phaseDurationDays: 10,
      weatherPool: {
        sunny: 0.2,
        cloudy: 0.2,
        overcast: 0.2,
        snow: 0.2,
        blizzard: 0.1,
        dust: 0.05,
        fog: 0.05,
      },
      description: '严寒的季节，生存变得更加困难',
    },
  },
  weathers: {
    sunny: {
      id: 'sunny',
      name: '晴天',
      iconId: 'icon_weather_sunny',
      weatherType: WeatherType.SUNNY,
      temperatureModifier: 5,
      visibility: 10,
      description: '天空晴朗，阳光明媚',
      movementSpeedModifier: 1.0,
      screenEffect: { type: 'none', intensity: 0 },
    },
    cloudy: {
      id: 'cloudy',
      name: '多云',
      iconId: 'icon_weather_cloudy',
      weatherType: WeatherType.CLOUDY,
      temperatureModifier: 3,
      visibility: 9,
      description: '天空被云层部分遮蔽',
      movementSpeedModifier: 1.0,
      screenEffect: { type: 'none', intensity: 0 },
    },
    overcast: {
      id: 'overcast',
      name: '阴天',
      iconId: 'icon_weather_overcast',
      weatherType: WeatherType.OVERCAST,
      temperatureModifier: 0,
      visibility: 8,
      description: '厚重的云层遮蔽了整个天空',
      movementSpeedModifier: 1.0,
      screenEffect: { type: 'none', intensity: 0 },
    },
    rain: {
      id: 'rain',
      name: '雨天',
      iconId: 'icon_weather_rain',
      weatherType: WeatherType.RAIN,
      temperatureModifier: -2,
      visibility: 6,
      description: '雨水从天而降，打湿了一切',
      movementSpeedModifier: 0.8,
      screenEffect: { type: 'rain', intensity: 0.6 },
    },
    snow: {
      id: 'snow',
      name: '雪天',
      iconId: 'icon_weather_snow',
      weatherType: WeatherType.SNOW,
      temperatureModifier: -2,
      visibility: 6,
      description: '雪花纷纷扬扬地飘落',
      movementSpeedModifier: 0.7,
      screenEffect: { type: 'snow', intensity: 0.6 },
    },
    storm: {
      id: 'storm',
      name: '暴雨',
      iconId: 'icon_weather_storm',
      weatherType: WeatherType.STORM,
      temperatureModifier: -5,
      visibility: 4,
      description: '狂风暴雨席卷全岛',
      movementSpeedModifier: 0.5,
      screenEffect: { type: 'rain', intensity: 1.0 },
    },
    blizzard: {
      id: 'blizzard',
      name: '暴雪',
      iconId: 'icon_weather_blizzard',
      weatherType: WeatherType.BLIZZARD,
      temperatureModifier: -5,
      visibility: 4,
      description: '猛烈的暴风雪，几乎看不清前方',
      movementSpeedModifier: 0.4,
      screenEffect: { type: 'snow', intensity: 1.0 },
    },
    fog: {
      id: 'fog',
      name: '雾',
      iconId: 'icon_weather_fog',
      weatherType: WeatherType.FOG,
      temperatureModifier: 0,
      visibility: 2,
      description: '浓雾弥漫，能见度极低',
      movementSpeedModifier: 0.6,
      screenEffect: { type: 'fog', intensity: 0.8 },
    },
    dust: {
      id: 'dust',
      name: '沙尘',
      iconId: 'icon_weather_dust',
      weatherType: WeatherType.DUST,
      temperatureModifier: 0,
      visibility: 3,
      description: '风沙漫天，呼吸变得困难',
      movementSpeedModifier: 0.6,
      screenEffect: { type: 'dust', intensity: 0.7 },
    },
    thunderstorm: {
      id: 'thunderstorm',
      name: '雷暴',
      iconId: 'icon_weather_thunderstorm',
      weatherType: WeatherType.THUNDERSTORM,
      temperatureModifier: -5,
      visibility: 4,
      description: '电闪雷鸣，暴雨倾盆',
      movementSpeedModifier: 0.5,
      screenEffect: { type: 'lightning', intensity: 0.8 },
    },
    acid_rain: {
      id: 'acid_rain',
      name: '酸雨',
      iconId: 'icon_weather_acid_rain',
      weatherType: WeatherType.ACID_RAIN,
      temperatureModifier: -2,
      visibility: 6,
      description: '雨水带着刺鼻的气味，灼烧着皮肤',
      movementSpeedModifier: 0.7,
      screenEffect: { type: 'rain', intensity: 0.7, colorFilter: '#88ff00' },
    },
    blood_rain: {
      id: 'blood_rain',
      name: '血雨',
      iconId: 'icon_weather_blood_rain',
      weatherType: WeatherType.BLOOD_RAIN,
      temperatureModifier: -5,
      visibility: 4,
      description: '猩红的雨水从天而降，仿佛天空在流血',
      movementSpeedModifier: 0.5,
      screenEffect: { type: 'rain', intensity: 0.9, colorFilter: '#ff0000' },
    },
  },
  timeOfDayConfigs: {
    [TimeOfDay.LATE_NIGHT]: {
      timeOfDay: TimeOfDay.LATE_NIGHT,
      name: '深夜',
      iconId: 'icon_time_late_night',
      startHour: 23,
      endHour: 2,
      ambientLight: 0.1,
      temperatureModifier: -5,
      sleepRecoveryMultiplier: 2.0,
      staminaConsumptionModifier: 0.5,
      backgroundColor: '#0a0a12',
    },
    [TimeOfDay.EARLY_MORNING]: {
      timeOfDay: TimeOfDay.EARLY_MORNING,
      name: '凌晨',
      iconId: 'icon_time_early_morning',
      startHour: 2,
      endHour: 5,
      ambientLight: 0.15,
      temperatureModifier: -3,
      sleepRecoveryMultiplier: 2.0,
      staminaConsumptionModifier: 0.5,
      backgroundColor: '#0e0e1a',
    },
    [TimeOfDay.DAWN]: {
      timeOfDay: TimeOfDay.DAWN,
      name: '清晨',
      iconId: 'icon_time_dawn',
      startHour: 5,
      endHour: 8,
      ambientLight: 0.5,
      temperatureModifier: 0,
      backgroundColor: '#1a1a30',
    },
    [TimeOfDay.MORNING]: {
      timeOfDay: TimeOfDay.MORNING,
      name: '上午',
      iconId: 'icon_time_morning',
      startHour: 8,
      endHour: 13,
      ambientLight: 0.9,
      temperatureModifier: 3,
      backgroundColor: '#2a2a4a',
    },
    [TimeOfDay.AFTERNOON]: {
      timeOfDay: TimeOfDay.AFTERNOON,
      name: '下午',
      iconId: 'icon_time_afternoon',
      startHour: 13,
      endHour: 18,
      ambientLight: 0.8,
      temperatureModifier: 5,
      backgroundColor: '#1e1e3a',
    },
    [TimeOfDay.DUSK]: {
      timeOfDay: TimeOfDay.DUSK,
      name: '傍晚',
      iconId: 'icon_time_dusk',
      startHour: 18,
      endHour: 21,
      ambientLight: 0.4,
      temperatureModifier: -1,
      backgroundColor: '#16162a',
    },
    [TimeOfDay.NIGHT]: {
      timeOfDay: TimeOfDay.NIGHT,
      name: '夜晚',
      iconId: 'icon_time_night',
      startHour: 21,
      endHour: 23,
      ambientLight: 0.2,
      temperatureModifier: -3,
      staminaConsumptionModifier: 0.5,
      backgroundColor: '#0e0e1a',
    },
  },
  corruption: {
    initialValue: 40,
    minValue: 0,
    maxValue: 100,
    thresholds: [
      {
        value: 25,
        name: '轻微腐化',
        description: '环境中开始出现微弱的异常迹象',
        rules: [
          {
            description: '敌人出现概率略微提升',
            affectedSystem: 'enemySpawn',
            params: { spawnWeightMultiplier: 1.2 },
          },
        ],
      },
      {
        value: 50,
        name: '中度腐化',
        description: '异常现象变得明显，生物变异加剧',
        rules: [
          {
            description: '敌人出现概率显著提升',
            affectedSystem: 'enemySpawn',
            params: { spawnWeightMultiplier: 1.5 },
          },
          {
            description: '场景描述开始出现异常',
            affectedSystem: 'sceneDescription',
            params: { anomalyProbability: 0.3 },
          },
        ],
      },
      {
        value: 75,
        name: '深度腐化',
        description: '整个岛屿陷入严重的腐化状态',
        rules: [
          {
            description: '敌人强度大幅提升',
            affectedSystem: 'enemySpawn',
            params: { spawnWeightMultiplier: 2.0, statMultiplier: 1.5 },
          },
          {
            description: '种植成功率下降',
            affectedSystem: 'farming',
            params: { successRateMultiplier: 0.5 },
          },
          {
            description: 'SAN值损失加速',
            affectedSystem: 'sanLoss',
            params: { lossMultiplier: 2.0 },
          },
        ],
      },
      {
        value: 95,
        name: '完全腐化',
        description: '现实与梦境的界限已经模糊',
        rules: [
          {
            description: '高等级梦境怪物大量出现',
            affectedSystem: 'enemySpawn',
            params: { dreamCreatureWeight: 100 },
          },
          {
            description: '所有场景描述严重异常',
            affectedSystem: 'sceneDescription',
            params: { anomalyProbability: 1.0 },
          },
        ],
      },
    ],
  },
  initialSeason: Season.SUMMER,
  initialSeasonPhase: SeasonPhase.EARLY,
  initialWeatherId: 'sunny',
  initialDay: 1,
  initialTimeMinutes: 480,
}