import type { EnemyDef } from '@/types/content'

export const enemies: EnemyDef[] = [
  {
    id: 'mutant_crab',
    name: '畸变蟹',
    description: '甲壳开裂，露出里面不该存在的牙齿。',
    hp: 28,
    damage: 6,
    armor: 2,
    sanLossOnSight: 3,
    skills: [
      {
        id: 'pinch',
        name: '钳击',
        skill: 'brawl',
        cooldown: 0,
        damageFormula: 'STR * BASE * 0.5',
        critChance: 'AGI / 100',
        critMultiplier: 1.5,
        staminaCost: 1,
      },
      {
        id: 'sweep',
        name: '横扫',
        skill: 'brawl',
        cooldown: 2,
        damageFormula: 'STR * BASE * 0.8',
        critChance: 'AGI / 100',
        critMultiplier: 1.5,
        staminaCost: 10,
      },
    ],
    loot: [{ itemId: 'wood', count: 10, chance: 1 }],
  },
  {
    id: 'mutant_dog',
    name: '扭曲猎犬',
    description: '多了一排关节的脊背，眼睛太多。',
    hp: 40,
    damage: 10,
    armor: 1,
    sanLossOnSight: 6,
    skills: [
      {
        id: 'bite',
        name: '撕咬',
        skill: 'brawl',
        cooldown: 0,
        damageFormula: 'BASE + 6',
      },
    ],
    loot: [
      { itemId: 'mutant_hide', count: 1, chance: 1 },
      { itemId: 'ration', count: 1, chance: 0.3 },
    ],
  },
  {
    id: 'mutant_chief',
    name: '变异人首领',
    description: '曾经是人。它邀请你加入合唱。',
    hp: 90,
    damage: 14,
    armor: 3,
    sanLossOnSight: 12,
    skills: [
      {
        id: 'sermon',
        name: '低语冲击',
        skill: 'brawl',
        cooldown: 1,
        damageFormula: 'BASE + 10',
      },
    ],
    loot: [{ itemId: 'scrap_metal', count: 3, chance: 1 }],
  },
  {
    id: 'sea_folk',
    name: '海民',
    description: '半人半鱼的畸变生物，眼中闪烁着疯狂的光芒。',
    hp: 45,
    damage: 10,
    armor: 3,
    sanLossOnSight: 5,
    skills: [
      {
        id: 'sea_shout',
        name: '海民大喝',
        skill: 'brawl',
        cooldown: 2,
        damageFormula: 'STR * BASE * 0.5 * LEVEL',
        critChance: 'AGI / 100',
        critMultiplier: 1.5,
        staminaCost: 1,
      },
    ],
    loot: [{ itemId: 'scrap_metal', count: 10, chance: 1 }],
  },
  {
    id: 'monkey',
    name: '变异猴子',
    description: '毛发脱落，皮肤呈现诡异的紫色，动作敏捷异常。',
    hp: 35,
    damage: 8,
    armor: 1,
    sanLossOnSight: 4,
    skills: [
      {
        id: 'scratch',
        name: '抓挠',
        skill: 'brawl',
        cooldown: 0,
        damageFormula: 'BASE + 5',
      },
    ],
    loot: [{ itemId: 'instant_noodles', count: 1, chance: 1 }],
  },
]
